### ISSUE TITLE
$VERSION=0.10; add new method get_job_details($job_name);

### ISSUE THREAD

**Issue by davehorner** [colinnewell/Jenkins-API#10]
Hello,
I was looking to get the detail behind the /job/{jobname}/api/json which includes the build history.  Hopefully my changes are acceptable.  I haven't tested locally yet, but it looks OK to me.  I've created a patch.  I will supply pull request: https://github.com/colinnewell/Jenkins-API/pull/11

Thanks for a great API.
--dave
http://dave.thehorners.com/

**Comment by colinnewell** [comment]
That's merged and I'll roll a new CPAN release shortly.

**Comment by davehorner** [comment]
Thank you very much for the merge of my change and your modifications.

I'd like to make it so that we can get details on the build.
one option would be to add an option build_id to the job details.
sub get_job_details
{
    my $self = shift;
    my $job_name = shift;
    my $build_id = shift;
    return $self->_json_api(['job', $job_name, $build_id, 'api', 'json'], @_) if($build_id);
    return $self->_json_api(['job', $job_name, 'api', 'json'], @_);
}

or create another method
sub get_build_details
{
    my $self = shift;
    my $job_name = shift;
    my $build_id = shift;
    return $self->_json_api(['job', $job_name, $build_id, 'api', 'json'], @_);
}

I am interested in extending the api to allow for additional path elements for custom plugins etc.
path_parts is very helpful to add elements in front of the std. elements provided by the method...
But it would be helpful to be able to add elements at the end of the url; before the 'api/json'
It would also be nice suppress 'api/json' so that people can request other return types, and use apis which do not end in api/json.

For instance, EnvInject+Plugin does not end in api/json and/or api endpoints which don't speak json.
https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin
<jenkins_url>/job/<job_name>/<build_number>/injectedEnvVars/export

All 5 calls of _json_api within Jenkins/API.pm have 'api','json' statically passed at the end making it hard to add elements before and after the static elements provided by the method...not to mention suppressing 'api/json'.

Since the change to support other types other than json/api and additional elements for the ending is a bit involved;
I will supply another pull request with the json/api 'api_type' parameter, including get_job_details with the optional build_id parameter.  Maybe you would prefer having another method get_build_details or with the extended _json method I'm providing, you can simply use the new parameter {path_ends=['whatever','you','need']}; no need for an additional parameter on get_job_details.

tested and working pull request to follow...
---
Additionally, 
 it might be worth sharing the url when a 'Invalid response' is caught.
For instance when I tried something like:
$jenkins->get_job_details('Test-Project/1')
I simply got Invalid reponse at /usr/local/share/perl/5.14.2/Jenkins/API.pm line 480.

die 'Invalid response:'.$uri->path_query unless $self->_client->responseCode eq '200';
would yield:
Invalid response:/job/Test-Project%2F1/api/json at /usr/local/share/perl/5.14.2/Jenkins/API.pm line 480.

**Comment by colinnewell** [comment]
I think a new method get_build_details would make the most sense.

With regards to wanting a general purpose api function the _json_api method should be left alone.  It will be simpler and more stable to simply create a brand new method that is designed for your general purpose from the outset.  The _json_api call is just a convenience for simple json calls.  

I assume that you primarily want the convenience of being able to build up the path using an array, passing query parameters and optionally decoding the response.

**Comment by davehorner** [comment]
I believe the changes are stable in that existing calls will not be broken.  I think removing the json/api from the calls to _json_api makes sense if you want to add elements to the end before the json/api...and even supress the json/api all together for strange endpoints which do not return json/api.

I do agree it makes the name of that function a little of a misnomer; renaming to _api_call or something might make more sense, but again I was looking to keep backward compat.

just a suggestion.
thanks.
--dave
