### ISSUE TITLE
$VERSION=0.11; _json_api improvements, get_job_details accepts optional $build_id, Invalid response includes url by davehorner

### ISSUE THREAD

**Issue by davehorner** [colinnewell/Jenkins-API#13]
Thank you very much for the merge of my change and your modifications (https://github.com/colinnewell/Jenkins-API/issues/10).

I'd like to make it so that we can get details on the build.
one option would be to add an option build_id to the job details.
sub get_job_details
{
    my $self = shift;
    my $job_name = shift;
    my $build_id = shift;
    return $self->_json_api(['job', $job_name, $build_id, 'api', 'json'], @_) if($build_id);
    return $self->_json_api(['job', $job_name, 'api', 'json'], @_);
}

or create another method
sub get_build_details
{
    my $self = shift;
    my $job_name = shift;
    my $build_id = shift;
    return $self->_json_api(['job', $job_name, $build_id, 'api', 'json'], @_);
}

I am interested in extending the api to allow for additional path elements for custom plugins etc.
path_parts is very helpful to add elements in front of the std. elements provided by the method...
But it would be helpful to be able to add elements at the end of the url; before the 'api/json'
It would also be nice suppress 'api/json' so that people can request other return types, and use apis which do not end in api/json.

For instance, EnvInject+Plugin does not end in api/json and/or api endpoints which don't speak json.
https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin
<jenkins_url>/job/<job_name>/<build_number>/injectedEnvVars/export

All 5 calls of _json_api within Jenkins/API.pm have 'api','json' statically passed at the end making it hard to add elements before and after the static elements provided by the method...not to mention suppressing 'api/json'.

Since the change to support other types other than json/api and additional elements for the ending is a bit involved;
I will supply another pull request with the json/api 'api_type' parameter, including get_job_details with the optional build_id parameter.  Maybe you would prefer having another method get_build_details or with the extended _json method I'm providing, you can simply use the new parameter {path_ends=['whatever','you','need']}; no need for an additional parameter on get_job_details.

tested and working pull request to follow...
---
https://github.com/colinnewell/Jenkins-API/pull/12

Additionally, 
 it might be worth sharing the url when a 'Invalid response' is caught.
For instance when I tried something like:
$jenkins->get_job_details('Test-Project/1')
I simply got Invalid reponse at /usr/local/share/perl/5.14.2/Jenkins/API.pm line 480.

die 'Invalid response:'.$uri->path_query unless $self->_client->responseCode eq '200';
would yield:
Invalid response:/job/Test-Project%2F1/api/json at /usr/local/share/perl/5.14.2/Jenkins/API.pm line 480.

**Comment by colinnewell** [comment]
I'm going to close this as most of the discussion about this has occurred on pull request #12.
