### ISSUE TITLE
Add a new general purpose api call method

### ISSUE THREAD

**Issue by colinnewell** [colinnewell/Jenkins-API#14]
This should be a `general_purpose_call` that allows use of arbitrary API methods on Jenkins.  Since Jenkins is extensible with plugins we can't predict or reliably support all the potential end points of the API so it makes sense to allow the user of the library specify some calls themselves.  Making use of the client with the authentication and the JSON decoding (where necessary) is a good idea.

Does this sort of method signature seem reasonable?

```perl
sub general_purpose_call
{
    my $self = shift;
    my $uri_parts = shift;
    my $args = shift;

    my $extra_params = $args->{extra_params};
    my $method = $args->{method} || 'GET';
    my $decode_json = exists $args->{decode_json} ? $args->{decode_json} : 1;
```

**Comment by davehorner** [comment]
We lost the path_parts (maybe better as path_begins?) and path_ends.  I pulled the code below from your last suggestion.  The name itself general_purpose_call with 20 characters is a bit large. general_call, jenkins_call, or better still api_call are easier on the eyes and hands; but its not a big deal to have a large name.

```perl
sub general_purpose_call
{
    my $self = shift;
    my $uri_parts = shift;
    my $args = shift;

    my $extra_params = $args->{extra_params};
    my $method = $args->{method} || 'GET';
    my $decode_json = exists $args->{decode_json} ? $args->{decode_json} : 1;
    my $path_begins = $args->{path_begins} || [];
    my $path_ends = $args->{path_ends} || [];

    my $uri = URI->new($self->base_url);
    $uri->path_segments(@$path_begins, @$uri_parts, @$path_ends);
    $uri->query_form($extra_params) if $extra_params;

    $self->_client->GET($uri->path_query);
    die 'Invalid response: '.$uri->path_query unless $self->_client->responseCode eq '200';
    my $response = $self->_client->responseContent();
    $response = JSON->new->utf8->decode($response) if($decode_json);
    return $response;
}
I like the idea of having method that allows for POST,etc. The above code doesn't use a general purpose method on _client to allow for specing the method type.  That is still to be done, but the above is still a good start.

Thanks for everything Colin.
--dave

**Comment by colinnewell** [comment]
To tell the truth I meant to loose path_begins and path_ends.  Since this is a new method do you really need 3 different parameters to pass in the various parts of the url?  All it is is a list of segments.

**Comment by davehorner** [comment]
The concept being that it allows for the extension of the existing functions if they start using this method instead of _json_api.  I'm still trying to get these extension points for the existing methods.

**Comment by colinnewell** [comment]
We can achieve that without needing to have those parameters in this call.  If the _json_api is converted to call this function it can build up the array so that it allows you to extend things.

**Comment by davehorner** [comment]
I understand; in that case yes, dropping them from this call makes sense.

**Comment by colinnewell** [comment]
I have created the method on a branch for now.  Does that meet your immediate requirements?

**Comment by davehorner** [comment]
Yes, thank you Colin.

**Comment by colinnewell** [comment]
I have pushed that to master and to CPAN.  I have logged the general extensibility of the methods to issue #15 which I think should be quite achievable now that we have this new method.

**Comment by davehorner** [comment]
I would prefer not having to wrap all the calls to general_call in exec do to the die, which is quite possible with 404s etc...  not that I have a great idea on how to properly pass the error outside of die; interested to hear if you have thoughts either way.

I also prefer a bit more information than just the 'Invalid response'.
 die 'Invalid response: '.$self->_client->responseCode.' : '.$uri->path_query unless $self->_client->responseCode eq $expected_response;

Thanks collin.
--dave

**Comment by colinnewell** [comment]
In general I believe that I'm providing access to everything you should need to deal with the error handling.  I'm reluctant to include lots of information or use a fancy library for throwing exceptions because people deal with errors in different ways.  The information is accessable as a first class citizen so you can do as complex or as simple error handling as you like.  If you want fancier error handling then wrapping it is probably the correct answer.  In theory you could just inherit from the object since it's just a `Moo` object and wrap the methods using `around`.  The new `failures` library is quite attractive, but I'm not sure I really want to force it on anyone.

```perl
# assuming use of Try::Tiny
try
{
    my $response = $api->general_call(...);
}
catch
{
    if($_ =~ /Invalid response/)
    {
        print "Fail - " . $api->response_code . "\n";
    }
};
```

**Comment by davehorner** [comment]
$uri->path_query is not available that I see, though it is constructed by the caller..somewhat.  It may be more suitable for the general call to return the response_code with the response in a returned list.  leaving the response check to the caller and removing the need to wrap. the caller can only expect the exception to be 'Invalid response', I don't think any of the library calls used within will die.  wrapping all the calls is also fine...

Thanks for the quick response,
--dave

**Comment by colinnewell** [comment]
You are correct that the URI is not available, but I'm not convinced that providing that is a worthwhile exercise.  I know that you needed to find it when you were first figuring out how the library worked as you tried to get it to do something it wasn't designed to do, but apart from that I don't believe that there is really a legitimate reason for needing it.  Perl is so easy to debug I don't really want to add lots of debugging code that might be useful when you are first learning how to use the module or trying to abuse it, but is then just redundant.
