### ISSUE TITLE
Feature request: timeout option

### ISSUE THREAD

**Issue by tordensen** [colinnewell/Jenkins-API#5]
Would you please add the timeout option which will pass to REST::Client as $client->setTimeout(NUM)

**Comment by davehorner** [comment]
private _data can be used, but preferred method is to use reader and writer methods.

http://search.cpan.org/~haarg/Moo-1.006001/lib/Moo.pm
reader=>'getClient'
writer=>'setClient'

that being said, it does work as-is without the reader/writer, just feels undocumented when using _attributes.
