### ISSUE TITLE
Authentication errors aren't obvious

### ISSUE THREAD

**Issue by colinnewell** [colinnewell/Jenkins-API#9]
Since Jenkins started using authentication for a lot of operations it would be worth improving the error handling so that they are easy to spot.  Perhaps throwing an exception.

**Comment by colinnewell** [comment]
This might just be a documentation issue.  It's technically possible to get all the information needed about the errors.  It might also be worth making a note of the API key that can be used by applications.

**Comment by davehorner** [comment]
I would suggest adding the api_key and api_pass attributes in the default example in the POD since most often people use some form of user auth.

my $jenkins = Jenkins::API->new({ base_url => 'http://jenkins:8080', api_key=>'username', api_pass=>'user token' });

**Comment by colinnewell** [comment]
I've updated the pod as suggested.
